[env:esp32-s3-super-mini]
platform = espressif32
; Switched to a native 4MB board target to override underlying framework defaults
board = esp32-s3-devkitc-1
framework = arduino

build_type = release
board_build.f_cpu = 240000000L
board_build.flash_mode = dio
board_build.f_flash = 80000000L

; HARD FORCED 4MB TIMINGS AND MAPS
board_upload.flash_size = 4MB
board_build.flash_size = 4MB
board_build.partitions = default.csv

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D ESP32S3_FLASH_SIZE_4MB      ; Explicit framework layout injection flag
    -O3
    -ffast-math
    -mfix-esp32-psram-cache-issue

lib_deps =
    freenove/Freenove WS2812 Lib for ESP32 @ ^1.0.5

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time